In [63]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [64]:
X,y = load_iris(return_X_y=True) ## to return input and output vals

In [65]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [66]:
from sklearn.naive_bayes import GaussianNB

In [67]:
gnb = GaussianNB()

In [68]:
gnb.fit(X_train,y_train)

GaussianNB()

In [69]:
y_pred = gnb.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [71]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [72]:
import seaborn as sns
df = sns.load_dataset('tips')

In [73]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [75]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [76]:
X = df.drop(['time','size'],axis=1)

In [77]:
y = df['time'].copy()

In [78]:
y = le3.fit_transform(y)

In [79]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [80]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])

In [81]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])

In [82]:
X_train

     total_bill   tip  sex  smoker   day
61        13.81  2.00    1       1   Sat
146       18.64  1.36    0       0  Thur
52        34.81  5.20    0       0   Sun
66        16.45  2.47    0       0   Sat
26        13.37  2.00    1       0   Sat
..          ...   ...  ...     ...   ...
67         3.07  1.00    0       1   Sat
192       28.44  2.56    1       1  Thur
117       10.65  1.50    0       0  Thur
47        32.40  6.00    1       0   Sun
172        7.25  5.15    1       1   Sun

[170 rows x 5 columns]

In [83]:
## Onehot encoding--- ColumnTrnasformer
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')

In [84]:
X_train=ct.fit_transform(X_train)

In [85]:
X_test=ct.transform(X_test)

In [86]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()

In [87]:
bnb.fit(X_train,y_train)

BernoulliNB()

In [88]:
y_pred = bnb.predict(X_test)

In [89]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[55  1]
 [ 5 13]]
0.918918918918919
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        56
           1       0.93      0.72      0.81        18

    accuracy                           0.92        74
   macro avg       0.92      0.85      0.88        74
weighted avg       0.92      0.92      0.92        74

In [90]:
!pip install nbformat

Defaulting to user installation because normal site-packages is not writeable
Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.5/78.5 kB ? eta 0:00:00
Requirement already satisfied: traitlets>=5.1 in c:\users\abhishek goswami\appdata\roaming\python\python310\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\abhishek goswami\appdata\roaming\python\python310\site-packages (from nbformat) (5.7.2)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.23.0-py3-none-any.whl (88 kB)
     ---------------------------------------- 88.5/88.5 kB 4.9 MB/s eta 0:00:00
Collecting fastjsonschema>=2.15
  Downloading fastjsonschema-2.21.1-py3-none-any.whl (23 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Downloading attrs-25.3.0-py3-none-any.whl (63 kB)
     ---------------------------------------- 63.8/63.8 kB ? eta 0:00:00
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.24.0-cp310-cp310-win_amd64.whl (234 kB)
     ------------------------------------- 234.6/234.6 kB 14.0 MB/s eta 0:00:00
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)
Requirement already satisfied: pywin32>=300 in c:\users\abhishek goswami\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (304)
Requirement already satisfied: platformdirs>=2.5 in c:\users\abhishek goswami\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (2.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\abhishek goswami\appdata\roaming\python\python310\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.13.1)
Installing collected packages: fastjsonschema, rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, nbformat
Successfully installed attrs-25.3.0 fastjsonschema-2.21.1 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 nbformat-5.10.4 referencing-0.36.2 rpds-py-0.24.0

[notice] A new release of pip available: 22.2.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip